// Seed data — converted 1:1 from the old frontend js/products.js PRODUCTS object.
// Prices are new (the old catalog only had "On Request") — adjust freely before running setup.

const BRANDS = [
  { id: 'rasasi',       name: 'Rasasi',        logo: '🌹' },
  { id: 'lattafa',      name: 'Lattafa',       logo: '🔮' },
  { id: 'rueBroca',     name: 'Rue Broca',     logo: '🌿' },
  { id: 'frenchAvenue', name: 'French Avenue', logo: '🗼' },
  { id: 'assaf',        name: 'Assaf',         logo: '🪔' },
  { id: 'afnan',        name: 'Afnan',         logo: '💎' },
  { id: 'rayhaan',      name: 'Rayhaan',       logo: '🌸' },
  { id: 'alHambra',     name: 'Al Hambra',     logo: '🏰' },
];

// price_cents is new — tune these to your real pricing before seeding.
const PRODUCTS = [
  { id: 'shuhrah',      name: 'Shuhrah',            brand_id: 'rasasi',       gender: 'Unisex', notes: ['Bergamot','Saffron','Rose Oud','Amber','White Musk'],        short_desc: 'Celebrity. Fame. Recognition. An oriental woody signature that commands attention.', full_desc: 'Shuhrah — meaning "fame" — opens with bergamot and saffron before settling into a rose-oud heart draped in amber.', badge: 'Bestseller', badge_class: 'badge-best', price_cents: 8900, intensity: 'Intense' },
  { id: 'hawasRasasi',  name: 'Hawas',              brand_id: 'rasasi',       gender: 'Men',    notes: ['Cardamom','Pepper','Juniper','Ambergris','Musk'],            short_desc: 'Fresh and powerful — Hawas is a scent of desire and strength for the modern man.', full_desc: 'Hawas by Rasasi is a bold aquatic-woody masculine fragrance. Cardamom and pepper open over a warm base of ambergris.', badge: 'Bestseller', badge_class: 'badge-best', price_cents: 6900, intensity: 'Strong' },
  { id: 'dakaRasasi',   name: 'Daka',               brand_id: 'rasasi',       gender: 'Men',    notes: ['Bergamot','Pineapple','Jasmine','Oud','Musk'],               short_desc: 'A woody oriental powerhouse with fresh citrus and deep oud.', full_desc: 'Daka by Rasasi is a sophisticated oriental blend where fresh bergamot and pineapple meet an oud-rich heart.', badge: '', badge_class: '', price_cents: 7500, intensity: 'Intense' },
  { id: 'raasiWomen',   name: 'Rasasi Pour Femme',  brand_id: 'rasasi',       gender: 'Women',  notes: ['Rose','Jasmine','Musk','Sandalwood','Vanilla'],              short_desc: 'A timeless feminine oriental, soft and radiant.', full_desc: 'Rasasi Pour Femme is an elegant floral-oriental designed for women who appreciate timeless luxury.', badge: '', badge_class: '', price_cents: 6500, intensity: 'Moderate' },

  { id: 'oudMoodEau',   name: 'Oud Mood Elixir',    brand_id: 'lattafa',      gender: 'Unisex', notes: ['Oud','Saffron','Rose','Sandalwood','Amber'],                 short_desc: 'A rich and smoky oriental oud elixir built for those who love depth.', full_desc: 'Oud Mood Elixir by Lattafa is a concentrated oriental blend of rich oud, warm saffron and precious rose.', badge: 'New Arrival', badge_class: 'badge-new', price_cents: 8200, intensity: 'Intense' },
  { id: 'yara',         name: 'Yara',               brand_id: 'lattafa',      gender: 'Women',  notes: ['Strawberry','Jasmine','Sandalwood','Musk','Vanilla'],        short_desc: 'Sweet, playful and magnetic — Yara is made for the confident modern woman.', full_desc: 'Yara by Lattafa is a fruity-floral feminine fragrance. Strawberry and jasmine bloom over a warm musky vanilla base.', badge: 'Bestseller', badge_class: 'badge-best', price_cents: 5500, intensity: 'Moderate' },
  { id: 'khamrahLat',   name: 'Khamrah',            brand_id: 'lattafa',      gender: 'Unisex', notes: ['Cinnamon','Oud','Vanilla','Musk','Amber'],                   short_desc: 'An addictive oriental blend of spice, oud and sweet vanilla.', full_desc: 'Khamrah by Lattafa is a warm and spicy oriental. Cinnamon and oud blend into a rich vanilla and amber drydown.', badge: '', badge_class: '', price_cents: 6900, intensity: 'Strong' },
  { id: 'asad',         name: 'Asad',               brand_id: 'lattafa',      gender: 'Men',    notes: ['Bergamot','Lavender','Oud','Sandalwood','Vetiver'],          short_desc: 'Bold. Fierce. Masculine. Asad means lion — and this fragrance lives up to the name.', full_desc: 'Asad by Lattafa opens with citrusy bergamot and crisp lavender before transitioning into a woody oud base.', badge: 'UAE Exclusive', badge_class: 'badge-exc', price_cents: 7200, intensity: 'Strong' },

  { id: 'oudAmber',     name: 'Oud & Amber',        brand_id: 'rueBroca',     gender: 'Unisex', notes: ['Oud','Amber','Rose','Musk','Cedarwood'],                     short_desc: 'A Parisian take on Arabic oud — refined, smoky and mysterious.', full_desc: 'Oud & Amber by Rue Broca is where Eastern oud tradition meets French perfumery elegance.', badge: '', badge_class: '', price_cents: 9500, intensity: 'Intense' },
  { id: 'pearlBlush',   name: 'Pearl Blush Musc',   brand_id: 'rueBroca',     gender: 'Women',  notes: ['Peach','White Rose','Musk','Sandalwood','Heliotrope'],      short_desc: 'Soft, feminine and enveloping — a musky peach floral of rare beauty.', full_desc: 'Pearl Blush Musc is a sensual musked floral. Peach and white rose bloom over a warm sandalwood and heliotrope base.', badge: 'New Arrival', badge_class: 'badge-new', price_cents: 8900, intensity: 'Light' },
  { id: 'musk',         name: 'White Musk',         brand_id: 'rueBroca',     gender: 'Musk',   notes: ['White Musk','Iris','Sandalwood','Vanilla','Cedarwood'],     short_desc: 'Pure, clean and hypnotic. The quintessential musk experience.', full_desc: 'White Musk by Rue Broca is a skin-close musk fragrance — clean, warm and deeply comforting.', badge: '', badge_class: '', price_cents: 5900, intensity: 'Light' },

  { id: 'faOud',        name: 'Oud Intense',        brand_id: 'frenchAvenue', gender: 'Men',    notes: ['Oud','Leather','Smoky Amber','Cedar','Vetiver'],            short_desc: 'Dark, leathery oud for the man who makes an entrance.', full_desc: 'Oud Intense by French Avenue is a powerful leather-oud fragrance built for presence. Smoky amber anchors the base.', badge: '', badge_class: '', price_cents: 8600, intensity: 'Intense' },
  { id: 'faRose',       name: 'Rose Noire',         brand_id: 'frenchAvenue', gender: 'Women',  notes: ['Dark Rose','Oud','Patchouli','Vanilla','Musk'],             short_desc: 'A dark romantic rose, laced with oud and mystery.', full_desc: 'Rose Noire is a deep floral oriental — dark Bulgarian rose entwined with oud and patchouli for a dramatic effect.', badge: 'Bestseller', badge_class: 'badge-best', price_cents: 7900, intensity: 'Moderate' },
  { id: 'faUnisex',     name: 'Neutral Oud',        brand_id: 'frenchAvenue', gender: 'Unisex', notes: ['Oud','Saffron','Incense','Benzoin','Sandalwood'],           short_desc: 'A gender-free oud built for lovers of the truly authentic.', full_desc: 'Neutral Oud by French Avenue strips fragrance down to its essence — pure oud, incense and resinous warmth.', badge: '', badge_class: '', price_cents: 8400, intensity: 'Intense' },

  { id: 'wildColt',     name: 'Wild Colt Bakhour',  brand_id: 'assaf',        gender: 'Unisex', notes: ['Oud','Amber Resin','Warm Spice','Cedarwood','Incense'],     short_desc: 'Earthy, bold and captivating. Bakhour-inspired artisanal fragrance.', full_desc: 'Wild Colt Bakhour is a tribute to the untamed spirit of Arabia. Rich oud and amber resins ignite over warm spice.', badge: 'New Arrival', badge_class: 'badge-new', price_cents: 7900, intensity: 'Strong' },
  { id: 'assafMusk',    name: 'Musk Al Assaf',      brand_id: 'assaf',        gender: 'Musk',   notes: ['Musk','Rose','Oud','Vanilla','Amber'],                      short_desc: 'A layered musk built around rose and oud — deeply personal and long-lasting.', full_desc: 'Musk Al Assaf is a signature musk fragrance. Soft rose and subtle oud melt into a creamy vanilla and amber base.', badge: '', badge_class: '', price_cents: 6200, intensity: 'Moderate' },
  { id: 'assafMen',     name: 'Black Stallion',     brand_id: 'assaf',        gender: 'Men',    notes: ['Tobacco','Leather','Oud','Cedarwood','Black Pepper'],       short_desc: 'Rugged, smoky and powerful — for the man who commands respect.', full_desc: 'Black Stallion by Assaf is a bold oriental masculine. Tobacco and leather ride over cedarwood and black pepper.', badge: '', badge_class: '', price_cents: 7500, intensity: 'Intense' },

  { id: 'supremeoud',   name: 'Supremacy Oud',      brand_id: 'afnan',        gender: 'Unisex', notes: ['Oud','Saffron','Rose','Sandalwood','Amber'],                 short_desc: 'One of the most acclaimed ouds in the UAE — deep, majestic and unforgettable.', full_desc: 'Supremacy Oud by Afnan is a masterclass in oud craftsmanship. Saffron and rose enhance a magnificent oud heart.', badge: 'Bestseller', badge_class: 'badge-best', price_cents: 9900, intensity: 'Intense' },
  { id: 'afnanWomen',   name: 'Inara White',        brand_id: 'afnan',        gender: 'Women',  notes: ['Peony','Lychee','Jasmine','Musk','Sandalwood'],             short_desc: 'Light, airy and feminine — a white floral dream.', full_desc: 'Inara White by Afnan is a fresh floral feminine. Peony and lychee open into a jasmine heart over a clean musk base.', badge: '', badge_class: '', price_cents: 6200, intensity: 'Light' },
  { id: 'ninePm',       name: '9 PM',               brand_id: 'afnan',        gender: 'Men',    notes: ['Apple','Lavender','Cinnamon','Vanilla','Musk'],             short_desc: 'Magnetic and seductive — the perfect evening fragrance for men.', full_desc: '9 PM by Afnan is a gourmand oriental masculine inspired by Parfums de Marly Herod. Apple and cinnamon over vanilla.', badge: 'UAE Exclusive', badge_class: 'badge-exc', price_cents: 6900, intensity: 'Moderate' },

  { id: 'ouloudRay',    name: 'Ou Loud',            brand_id: 'rayhaan',      gender: 'Unisex', notes: ['Oud','Bergamot','Rose','Patchouli','Incense'],              short_desc: 'An intimate, smoky oud fragrance that lingers like a memory.', full_desc: 'Ou Loud by Rayhaan by Rotana is a deep oriental oud composition. Bergamot and rose soften the heavy oud and incense.', badge: '', badge_class: '', price_cents: 7900, intensity: 'Intense' },
  { id: 'rayhaanWomen', name: 'Blossom',            brand_id: 'rayhaan',      gender: 'Women',  notes: ['Magnolia','Freesia','Musk','Cedarwood','Peach'],            short_desc: 'Fresh, blooming and delicate — femininity in a bottle.', full_desc: 'Blossom by Rayhaan is a light floral feminine. Magnolia and freesia float over a clean musky cedarwood base.', badge: '', badge_class: '', price_cents: 5900, intensity: 'Light' },
  { id: 'rayhaanMen',   name: 'Epic',               brand_id: 'rayhaan',      gender: 'Men',    notes: ['Saffron','Oud','Musk','Amber','Sandalwood'],                short_desc: 'Epic by name, epic by nature — a saffron-oud oriental for men.', full_desc: 'Epic by Rayhaan is a bold masculine oriental. Saffron and oud unfold over a warm musk and amber base.', badge: '', badge_class: '', price_cents: 7200, intensity: 'Strong' },

  { id: 'hawasEclat',   name: 'Hawas Éclat',        brand_id: 'alHambra',     gender: 'Women',  notes: ['Pink Guava','Sea Breeze','Jasmine','Soft Musk','Sandalwood'], short_desc: 'A luminous floral-aquatic for the modern woman — pink and shimmering.', full_desc: 'Hawas Éclat is a radiant interpretation of desire. Aquatic freshness meets floral depth in this Diamond Collection gem.', badge: 'Bestseller', badge_class: 'badge-best', price_cents: 6900, intensity: 'Moderate' },
  { id: 'alHambraMen',  name: 'Sultan',             brand_id: 'alHambra',     gender: 'Men',    notes: ['Cardamom','Leather','Oud','Amber','Cedarwood'],             short_desc: 'Regal, authoritative and unmistakably masculine.', full_desc: 'Sultan by Al Hambra is an opulent oriental masculine. Cardamom and leather give way to a rich oud and amber base.', badge: '', badge_class: '', price_cents: 7500, intensity: 'Intense' },
  { id: 'alHambraMusk', name: 'Pure Musk',          brand_id: 'alHambra',     gender: 'Musk',   notes: ['White Musk','Amber','Rose','Powdery Iris','Vanilla'],       short_desc: 'Silky, skin-close and beautifully powdery musk.', full_desc: 'Pure Musk by Al Hambra is a soft, cocooning musk. White musk and powdery iris blend with a gentle vanilla warmth.', badge: '', badge_class: '', price_cents: 5500, intensity: 'Light' },
];

// Demo account — only admins log in. Customers check out as guests (no account).
const DEMO_USERS = [
  { name: 'Admin User', email: 'admin@abs.com', password: 'admin123', role: 'admin', phone: '', address: '' },
];

// Homepage testimonials — admin-curated (no public submission flow), so this
// is the only place new ones get added; the dashboard can only delete.
const REVIEWS = [
  { id: 'review-rami',  stars: 5, review_text: "I ordered Shuhrah on a whim and it completely replaced my go-to scent. The longevity is insane — people ask me all day what I'm wearing.", author_name: 'Rami K.', author_location: 'Beirut, Lebanon', product_label: 'Shuhrah · Rasasi' },
  { id: 'review-lara',  stars: 5, review_text: 'Hawas Éclat is absolutely dreamy. Light, feminine, and incredibly elegant. Delivery was fast and the packaging was beautiful. Will order again!', author_name: 'Lara M.', author_location: 'Jounieh, Lebanon', product_label: 'Hawas Éclat · Al Hambra' },
  { id: 'review-karim', stars: 5, review_text: 'Finally found a place that brings real UAE fragrances to Lebanon. Wild Colt Bakhour is a masterpiece — deep, warm, and totally unique.', author_name: 'Karim A.', author_location: 'Tripoli, Lebanon', product_label: 'Wild Colt Bakhour · Assaf' },
  { id: 'review-nour',  stars: 5, review_text: 'The service through WhatsApp was so personal and easy. They helped me pick the perfect gift for my husband. He loved it. Highly recommend.', author_name: 'Nour S.', author_location: 'Sidon, Lebanon', product_label: 'Gift Order · Lattafa' },
  { id: 'review-tarek', stars: 5, review_text: 'Ordered three bottles at once and every single one exceeded my expectations. The scents are authentic UAE quality — not diluted or fake like other places.', author_name: 'Tarek H.', author_location: 'Zahle, Lebanon', product_label: 'Multiple Orders · Rasasi & Afnan' },
  { id: 'review-maya',  stars: 5, review_text: "I was skeptical at first but after trying a sample they recommended I was hooked. Abs Fragrances has the best curation I've seen in Lebanon.", author_name: 'Maya R.', author_location: 'Baabda, Lebanon', product_label: 'Rue Broca Collection' },
];

module.exports = { BRANDS, PRODUCTS, DEMO_USERS, REVIEWS };
